### ISSUE TITLE
Remove .open monkey patching in the Bag class

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/rosbag#17]
https://github.com/foxglove/rosbag/blob/main/src/node/index.ts#L88

Rather than having node and web folders that re-export the same things and add a reader by money patching the .open static method on the Bag class, we can have two separate classes NodeFileReader and DomFileReader within `src` and the user can use the one appropriate for their platform directly when making a Bag instance.

We should also combine the Bag class and the BagReader so that initializing becomes:

```typescript
const bag = new Bag(new NodeFileReader(filename));
// or maybe
const bag = await Bag.open(new DomFileReader(blobOrFile));
```

Thus eliminating keeping the entry points in sync and making it explicit at the call site which reader is used.

**Comment by jtbandes** [comment]
> we can have two separate classes NodeFileReader and DomFileReader within `src`

If we build these with the same tsconfig, there is no way to have a `lib` setting that differs between files. It might be preferable to just have multiple build targets in the package, or even just multiple packages as we do with rosbag2-node/web.
