### ISSUE TITLE
Question: Change list anywhere?

### ISSUE THREAD

**Issue by gkjohnson** [foxglove/rosbag#36]
Hey guys! I'm planning switch over to use this library because it seems to be your more maintained / updated fork of [rosbag.js](https://github.com/cruise-automation/rosbag.js) -- are you guys keeping a change log anywhere I can check out? I'd like to take a look at what's changed between versions so I can keep up to date more easily.

Thanks!

**Comment by defunctzombie** [comment]
There is not. I will add one to this repo and populate it with changes between rosbag.js and our 0.1.0 version. From there we will maintain the changelog against our versions.

**Comment by defunctzombie** [comment]
I've added a changelog file with notes on changes from rosbag.js to 0.1.0.

Before we publish a v1 we'll likely tackle #25 and #27 which will be API breaking changes.

**Comment by gkjohnson** [comment]
Excellent, thank you! I'll wait until 1.0.0 to switch over, then.
