### ISSUE TITLE
Sourcemaps cause warnings because src files are not included in distribution

### ISSUE THREAD

**Issue by gkjohnson** [foxglove/rosbag#42]
Hello again! I'm seeing some other warnings with Webpack when building a project with rosbag as a dependency because the src files are not included in the distribution but are referenced via the source maps:

```
WARNING in ./node_modules/@foxglove/rosbag/dist/esm/record.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '<local path>/node_modules/@foxglove/rosbag/src/record.ts' file: Error: ENOENT: no such file or directory, open '<local path>/node_modules/@foxglove/rosbag/src/record.ts'
```

In the source map files those original source files are referenced:

```js
{
  "version":3,
  "file":"fields.js",
  "sourceRoot":"",
  "sources":["../../src/fields.ts"],
  "names":[]
  // ...
}
```

I believe adding the "src" folder to the list of [published files](https://github.com/foxglove/rosbag/blob/main/package.json#L12-L18) would fix this.

**Comment by defunctzombie** [comment]
Another option is to use the inlineSources (https://www.typescriptlang.org/tsconfig/#inlineSources) option to include the sources in the .map files

**Comment by amacneil** [comment]
Would be nice to be consistent across all our packages. Most include `src` in the package. If we don't want to ship sources, then we should also not ship source maps.

**Comment by gkjohnson** [comment]
Great thanks guys!
